Repository mudita/MuditaOS, pull requests merged in 2021-12, with the labels that each got.

#3364 [EGD-8056] Fix new messages string
  image/assets/lang/Polski.json
Labels: i18n

#3365 [EGD-7909] Fix Retry mode change on fail
  module-services/service-cellular/ServiceCellular.cpp
  module-services/service-cellular/connection-manager/ConnectionManager.cpp
  module-services/service-cellular/connection-manager/ConnectionManagerCellularCommands.cpp
  module-services/service-cellular/service-cellular/CellularMessage.hpp
  module-services/service-cellular/service-cellular/connection-manager/ConnectionManager.hpp
  module-services/service-cellular/service-cellular/connection-manager/ConnectionManagerCellularCommands.hpp
  module-services/service-cellular/service-cellular/connection-manager/ConnectionManagerCellularCommandsInterface.hpp
  module-services/service-cellular/src/SimCard.hpp
  module-services/service-cellular/tests/unittest_connection-manager.cpp
Labels: cellular, team-delta

#3338 [EGD-7871] Fix refreshing calllog details after editing contact
  module-apps/application-calllog/windows/CallLogDetailsWindow.cpp
  module-apps/application-calllog/windows/CallLogDetailsWindow.hpp
Labels: bug, gui, team-delta

#3400 [EGD-7920] Fix GUI in adding / removing contacts
  module-apps/application-phonebook/models/NewContactModel.cpp
  module-apps/application-phonebook/models/NewContactModel.hpp
  module-apps/application-phonebook/windows/PhonebookNewContact.cpp
Labels: bug, gui, team-delta

#3430 [EGD-8121] Fix cellular sleep mode enter without SIM
  module-services/service-cellular/ServiceCellular.cpp
Labels: bug, cellular, team-delta
