Repository mudita/MuditaOS, pull requests merged in 2022-12, with the labels that each got.

#4178 [BH-1415] Front light intensity for pre-wake up and main alarm
  harmony_changelog.md
  image/assets/lang/English.json
  image/user/db/settings_bell_002.sql
  products/BellHybrid/alarms/src/actions/FrontlightAction.cpp
  products/BellHybrid/alarms/src/actions/FrontlightAction.hpp
  products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
  products/BellHybrid/apps/application-bell-settings/models/FrontlightModel.cpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AbstractPrewakeUpSettingsModel.hpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsListItemProvider.cpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsListItemProvider.hpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/AlarmSettingsModel.cpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpListItemProvider.cpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpListItemProvider.hpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpSettingsModel.cpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/PrewakeUpSettingsModel.hpp
  products/BellHybrid/apps/application-bell-settings/models/alarm_settings/SettingsListItemProvider.hpp
  products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp
  products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.hpp
  products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/PrewakeUpPresenter.cpp
  products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/PrewakeUpPresenter.hpp
  products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.cpp
  products/BellHybrid/apps/application-bell-settings/windows/alarm_settings/BellSettingsAlarmSettingsWindow.hpp
  products/BellHybrid/apps/common/CMakeLists.txt
  products/BellHybrid/apps/common/include/common/data/FrontlightUtils.hpp
  products/BellHybrid/apps/common/include/common/models/AbstractAlarmSettingsModel.hpp
  products/BellHybrid/apps/common/include/common/models/AlarmSettingsModel.hpp
  products/BellHybrid/apps/common/include/common/models/FrontlightModel.hpp
  products/BellHybrid/services/db/include/db/SystemSettings.hpp
Labels: gui

#4190 [MOS-831] Fix screen lock during onboarding
  module-apps/application-onboarding/ApplicationOnBoarding.cpp
  pure_changelog.md
Labels: bug, gui

#4195 [MOS-717] Add pop-up about SIM removed/inserted in all apps
  module-apps/application-alarm-clock/ApplicationAlarmClock.cpp
  module-apps/application-antenna/ApplicationAntenna.cpp
  module-apps/application-calculator/ApplicationCalculator.cpp
  module-apps/application-calendar/ApplicationCalendar.cpp
  module-apps/application-call/ApplicationCall.cpp
  module-apps/application-calllog/ApplicationCallLog.cpp
  module-apps/application-meditation/ApplicationMeditation.cpp
  module-apps/application-messages/ApplicationMessages.cpp
  module-apps/application-music-player/ApplicationMusicPlayer.cpp
  module-apps/application-notes/ApplicationNotes.cpp
  module-apps/application-phonebook/ApplicationPhonebook.cpp
  pure_changelog.md
Labels: cellular, gui

#4216 [MOS-837] Add contextual text "process in progress" in SIM popup
  image/assets/lang/Deutsch.json
  image/assets/lang/English.json
  image/assets/lang/Espanol.json
  image/assets/lang/Francais.json
  image/assets/lang/Polski.json
  module-apps/application-onboarding/ApplicationOnBoarding.hpp
  module-apps/application-onboarding/CMakeLists.txt
  module-apps/application-onboarding/Constants.hpp
  module-apps/apps-common/popups/lock-popups/SimSwitchingWindow.cpp
Labels: gui

#4220 [MOS-160] Fix broken text on SIM selection screen
  image/assets/lang/Deutsch.json
  image/assets/lang/Francais.json
  pure_changelog.md
Labels: bug, gui

#4221 [MOS-159] Fix broken text on the PIN input screen
  image/assets/lang/Espanol.json
  pure_changelog.md
Labels: bug, gui

#4223 [MOS-836] Fix for selecting SIM during onboarding
  module-apps/application-onboarding/ApplicationOnBoarding.cpp
Labels: bug
