Repository mudita/MuditaOS, pull requests merged in 2022-02, with the labels that each got.

#3538 [EGD-8225] Fix incorrect logs of Power Manager Efficiency
  module-sys/SystemManager/include/SystemManager/PowerManager.hpp
Labels: bug, team-delta

#3540 [CP-1005] Macflash tool to flash Pure on macOS
  tools/macflash.sh
  tools/macflash_setup.sh
Labels: build

#3550 [EGD-8258] Fix directory name in config scripts
  config/bootstrap.sh
  config/run_runner_docker
Labels: community

#3563 [MOS-144] Fix Increased CPU usage
  module-services/service-evtmgr/EventManager.cpp
  module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp
  module-sys/SystemManager/CpuSentinel.cpp
  module-sys/SystemManager/include/SystemManager/CpuSentinel.hpp
  module-sys/SystemManager/tests/unittest_CpuSentinelsGovernor.cpp
Labels: bug

#3523 [EGD-8128] Baudrate change for cellular transmission
  module-services/service-cellular/ServiceCellular.cpp
  module-services/service-cellular/service-cellular/ServiceCellular.hpp
Labels: cellular, team-delta

#3585 [CP-1033] Add Outbox endpoint to service-desktop
  module-services/service-desktop/CMakeLists.txt
  module-services/service-desktop/ServiceDesktop.cpp
  module-services/service-desktop/WorkerDesktop.cpp
  module-services/service-desktop/WorkerDesktop.hpp
  module-services/service-desktop/endpoints/include/endpoints/EndpointType.hpp
  module-services/service-desktop/endpoints/include/endpoints/JsonKeyNames.hpp
  module-services/service-desktop/include/service-desktop/Outbox.hpp
  module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
  module-services/service-desktop/parser/MessageHandler.cpp
  module-services/service-desktop/parser/MessageHandler.hpp
  products/PurePhone/services/desktop/endpoints/CMakeLists.txt
  products/PurePhone/services/desktop/endpoints/EndpointFactoryPure.cpp
  products/PurePhone/services/desktop/endpoints/include/endpoints/outbox/OutboxEndpoint.hpp
  products/PurePhone/services/desktop/endpoints/include/endpoints/outbox/OutboxHelper.hpp
  products/PurePhone/services/desktop/endpoints/outbox/OutboxEndpoint.cpp
  products/PurePhone/services/desktop/endpoints/outbox/OutboxHelper.cpp
Labels: desktop-service

#3595 [MOS-245] Fix errant spaces
  module-apps/application-music-player/data/MusicPlayerStyle.hpp
  module-audio/Audio/Audio.cpp
  module-audio/board/rt1051/puretx/RT1051CellularAudio.cpp
  module-bsp/board/rt1051/bellpx/audio.cpp
  module-bsp/board/rt1051/bellpx/board/BoardDefinitions.hpp
  module-bsp/board/rt1051/bsp/audio/Codec.hpp
  module-bsp/board/rt1051/bsp/eink/bsp_eink.cpp
  module-bsp/board/rt1051/drivers/RT1051DriverI2C.cpp
  module-bsp/board/rt1051/drivers/RT1051DriverSAI.cpp
  module-bsp/board/rt1051/eMMC/eMMC.cpp
  module-bsp/board/rt1051/puretx/audio.cpp
  module-bsp/board/rt1051/puretx/board/BoardDefinitions.hpp
  module-bsp/drivers/dma/DriverDMA.cpp
  module-bsp/drivers/dma/DriverDMA.hpp
  module-bsp/drivers/dmamux/DriverDMAMux.cpp
  module-bsp/drivers/dmamux/DriverDMAMux.hpp
  module-bsp/drivers/gpio/DriverGPIO.cpp
  module-bsp/drivers/gpio/DriverGPIO.hpp
  module-bsp/drivers/i2c/DriverI2C.cpp
  module-bsp/drivers/i2c/DriverI2C.hpp
  module-bsp/drivers/pll/DriverPLL.cpp
  module-bsp/drivers/pll/DriverPLL.hpp
  module-cellular/modem/mux/CellularMux.cpp
  module-db/Interface/ContactRecord.cpp
  module-db/Interface/SMSRecord.cpp
  module-db/Tables/ContactsAddressTable.cpp
  module-db/Tables/ContactsNameTable.cpp
  module-db/Tables/ContactsNumberTable.cpp
  module-db/Tables/ContactsRingtonesTable.cpp
  module-db/Tables/ContactsTable.cpp
  module-db/Tables/NotesTable.cpp
  module-db/Tables/SMSTable.cpp
  module-db/Tables/ThreadsTable.cpp
  module-db/queries/phonebook/QueryContactGet.cpp
  module-db/tests/ContactsRecord_tests.cpp
  module-db/tests/SMSRecord_tests.cpp
  module-db/tests/SMSTable_tests.cpp
  module-db/tests/ThreadRecord_tests.cpp
  module-db/tests/ThreadsTable_tests.cpp
  module-services/service-antenna/ServiceAntenna.cpp
  module-services/service-appmgr/model/ApplicationManagerCommon.cpp
  module-services/service-cellular/ServiceCellular.cpp
  module-services/service-db/messages/DBCalllogMessage.cpp
  module-services/service-db/messages/DBContactMessage.cpp
  module-services/service-desktop/tests/unittest.cpp
  module-services/service-eink/ServiceEink.cpp
  module-services/service-evtmgr/EventManager.cpp
  module-sys/Service/details/bus/Bus.cpp
  products/BellHybrid/apps/application-bell-alarm/presenter/BellAlarmSetPresenter.cpp
  products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationProgressPresenter.cpp
  products/BellHybrid/apps/application-bell-meditation-timer/presenter/MeditationTimerPresenter.cpp
  products/BellHybrid/apps/application-bell-meditation-timer/windows/MeditationTimerWindow.cpp
  products/BellHybrid/apps/application-bell-powernap/data/PowerNapListItem.cpp
  products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapSessionEndedPresenter.cpp
  products/BellHybrid/apps/common/src/popups/presenter/AlarmActivatedPresenter.cpp
  products/PurePhone/services/desktop/endpoints/contacts/ContactHelper.cpp
Labels: community
