Repository mudita/MuditaOS, pull requests merged in 2022-03, with the labels that each got.

#3619 [MOS-244] Change label title above favorite contacts
  image/assets/lang/Deutsch.json
  image/assets/lang/English.json
  image/assets/lang/Espanol.json
  image/assets/lang/Francais.json
  image/assets/lang/Polski.json
  image/assets/lang/Svenska.json
  module-apps/application-phonebook/widgets/PhonebookItem.cpp
Labels: gui

#3610 [MOS-16] Change favourite contacts font to regular
  module-apps/application-phonebook/widgets/PhonebookItem.cpp
  module-apps/application-phonebook/widgets/PhonebookItem.hpp
Labels: gui

#3631 [MOS-256] Turn off torch driver when not in use
  module-bsp/board/linux/torch/torch.cpp
  module-bsp/board/rt1051/bsp/torch/torch.cpp
  module-bsp/bsp/torch/torch.hpp
  module-services/service-evtmgr/api/torch.cpp
  products/PurePhone/services/evtmgr/EventManager.cpp
Labels: hw

#3573 [MOS-218] Fix broken documentation links
  doc/adding_unittests.md
  doc/quickstart.md
  doc/setup_ide.md
Labels: community

#3571 [MOS-219] Expand "Setup IDE" to include QtCreator
  doc/setup_ide.md
Labels: community

#3637 [MOS-45] Invalid number decoding
  module-utils/unicode/utf8/test/unittest_utf8.cpp
  module-utils/unicode/utf8/utf8/UTF8.cpp
  module-utils/unicode/utf8/utf8/UTF8.hpp
Labels: cellular

#3679 [MOS-338] Fix regression in the frequency stepping algorithm
  module-sys/SystemManager/cpu/algorithm/FrequencyStepping.cpp
  module-sys/SystemManager/cpu/algorithm/FrequencyStepping.hpp
Labels: bug

#3689 [MOS-337] Fix no audio for incoming calls/messages
  module-services/service-cellular/call/CallAudio.cpp
Labels: bug, cellular, audio

#3697 [MOS-360] Fix battery charger stack overflow
  module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
Labels: bug, stack
