Repository mudita/MuditaOS, pull requests merged in 2022-07, with the labels that each got.

#3956 MOS-586-crash-of-pure-simulator-while-navigating-into-settings-phone-modes
  module-apps/application-settings/windows/phone-modes/PhoneModesWindow.cpp
Labels: bug

#3962 [MOS-210] Avoid blocking of key handling, artificially generate Release
  module-services/service-evtmgr/WorkerEventCommon.cpp
  module-services/service-evtmgr/service-evtmgr/WorkerEventCommon.hpp
Labels: bug

#3963 [MOS-569] Fix incorrect navtext in onboarding for time zone and date time
  module-apps/application-onboarding/windows/OnBoardingDateAndTimeWindow.cpp
Labels: bug

#3957 [MOS-510] Fix wrong charger configuration
  module-bsp/board/rt1051/CMakeLists.txt
  module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.cpp
  module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.hpp
  module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger_utils.hpp
  module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
Labels: bug, hw

#3990 [MOS-598] Improved keyboard responsiveness
  module-sys/SystemManager/CpuGovernor.cpp
  products/PurePhone/services/evtmgr/CMakeLists.txt
  products/PurePhone/services/evtmgr/EventManager.cpp
  products/PurePhone/services/evtmgr/include/evtmgr/EventManager.hpp
  products/PurePhone/services/evtmgr/include/evtmgr/UserActivityHandler.hpp
  products/PurePhone/services/evtmgr/user-activity-handler/UserActivityHandler.cpp
Labels: hw
