Repository mudita/MuditaOS, pull requests merged in 2022-11, with the labels that each got.

#4129 [MOS-788] Fix incorrect total CPU usage in logs
  module-sys/SystemManager/PowerManager.cpp
  pure_changelog.md
Labels: bug

#4105 [BH-1557] Change Harmony home screen font to bigger one
  harmony_changelog.md
  module-apps/apps-common/widgets/BellBaseLayout.cpp
  module-apps/apps-common/widgets/BellBaseLayout.hpp
  module-apps/apps-common/widgets/TimeSetFmtSpinner.hpp
  module-apps/apps-common/widgets/TimeSetSpinner.hpp
  module-gui/gui/core/FontInfo.cpp
  module-gui/gui/core/FontInfo.hpp
  module-gui/gui/widgets/Style.hpp
  products/BellHybrid/CMakeLists.txt
  products/BellHybrid/apps/common/include/common/data/BellMainStyle.hpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithAmPm.cpp
  products/BellHybrid/assets/assets_proprietary.json
Labels: gui

#4130 [BH-1594] Add shortcuts instruction
  art/bell/shortcuts_step_bedside_lamp_W_G.png
  art/bell/shortcuts_step_deep_press_W_G.png
  art/bell/shortcuts_step_home_and_battery_W_G.png
  art/bell/shortcuts_step_light_click_W_G.png
  art/bell/shortcuts_step_restart_W_G.png
  art/bell/shortcuts_step_rotate_W_G.png
  art/bell/shortcuts_step_turn_off_W_G.png
  harmony_changelog.md
  image/assets/lang/English.json
  module-apps/apps-common/widgets/BellBaseLayout.hpp
  products/BellHybrid/CMakeLists.txt
  products/BellHybrid/apps/application-bell-onboarding/ApplicationBellOnBoarding.cpp
  products/BellHybrid/apps/application-bell-onboarding/CMakeLists.txt
  products/BellHybrid/apps/application-bell-onboarding/include/application-bell-onboarding/BellOnBoardingNames.hpp
  products/BellHybrid/apps/application-bell-onboarding/layouts/OnBoardingShortcutsLayoutClassic.cpp
  products/BellHybrid/apps/application-bell-onboarding/layouts/OnBoardingShortcutsLayoutClassic.hpp
  products/BellHybrid/apps/application-bell-onboarding/layouts/OnBoardingShortcutsLayoutProvider.hpp
  products/BellHybrid/apps/application-bell-onboarding/layouts/OnBoardingShortcutsLayouts.cpp
  products/BellHybrid/apps/application-bell-onboarding/layouts/OnBoardingShortcutsLayouts.hpp
  products/BellHybrid/apps/application-bell-onboarding/presenter/OnBoardingShortcutsWindowPresenter.cpp
  products/BellHybrid/apps/application-bell-onboarding/presenter/OnBoardingShortcutsWindowPresenter.hpp
  products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingSettingsWindow.cpp
  products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingShortcutsOptionWindow.cpp
  products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingShortcutsOptionWindow.hpp
  products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingShortcutsWindow.cpp
  products/BellHybrid/apps/application-bell-onboarding/windows/OnBoardingShortcutsWindow.hpp
  products/BellHybrid/apps/application-bell-settings/include/application-bell-settings/windows/BellSettingsTimeUnitsWindow.hpp
  products/BellHybrid/apps/application-bell-settings/windows/BellSettingsTimeUnitsWindow.cpp
  products/BellHybrid/apps/common/src/options/BellShortOptionWindow.cpp
  products/BellHybrid/assets/assets_common.json
Labels: gui

#4139 [MOS-641] Fix SIM cards window
  image/assets/lang/Deutsch.json
  image/assets/lang/English.json
  image/assets/lang/Espanol.json
  image/assets/lang/Francais.json
  image/assets/lang/Polski.json
  image/assets/lang/Svenska.json
  module-apps/application-settings/ApplicationSettings.cpp
  module-apps/application-settings/include/application-settings/ApplicationSettings.hpp
  module-apps/application-settings/presenter/network/SimPINSettingsPresenter.cpp
  module-apps/application-settings/windows/network/SimCardsWindow.cpp
  module-apps/application-settings/windows/network/SimCardsWindow.hpp
  module-apps/apps-common/locks/data/SimLockMessages.hpp
  module-apps/apps-common/locks/handlers/SimLockHandler.cpp
  module-apps/apps-common/locks/handlers/SimLockHandler.hpp
  module-apps/apps-common/locks/handlers/SimLockSubject.cpp
  module-apps/apps-common/locks/handlers/SimLockSubject.hpp
  module-gui/gui/widgets/status-bar/SIM.cpp
  module-services/service-cellular/include/service-cellular/api/common.hpp
  module-services/service-cellular/include/service-cellular/api/request/sim.hpp
  module-services/service-cellular/src/ServiceCellularPriv.cpp
  module-services/service-cellular/src/SimCard.cpp
  module-services/service-cellular/src/SimCard.hpp
  module-utils/EventStore/EventStore.hpp
  products/PurePhone/services/appmgr/ApplicationManager.cpp
  products/PurePhone/sys/SystemManager.cpp
  pure_changelog.md
Labels: bug, gui

#4161 [MOS-660] Fix disappearing button in PIN entering screen
  module-apps/apps-common/locks/widgets/SimLockBox.cpp
  module-apps/apps-common/popups/lock-popups/SimLockInputWindow.cpp
  pure_changelog.md
Labels: bug, gui

#4150 [MOS-800] Add a popup for changing the SIM card
  image/assets/lang/Deutsch.json
  image/assets/lang/English.json
  image/assets/lang/Espanol.json
  image/assets/lang/Francais.json
  image/assets/lang/Polski.json
  module-apps/application-onboarding/windows/OnBoardingSimSelectWindow.cpp
  module-apps/application-settings/windows/network/SimCardsWindow.cpp
  module-apps/apps-common/locks/data/SimLockMessages.hpp
  module-apps/apps-common/locks/handlers/SimLockHandler.cpp
  module-apps/apps-common/locks/handlers/SimLockHandler.hpp
  module-apps/apps-common/locks/handlers/SimLockSubject.cpp
  module-apps/apps-common/locks/handlers/SimLockSubject.hpp
  module-apps/apps-common/popups/CMakeLists.txt
  module-apps/apps-common/popups/Popups.cpp
  module-apps/apps-common/popups/Popups.hpp
  module-apps/apps-common/popups/lock-popups/SimSwitchingWindow.cpp
  module-apps/apps-common/popups/lock-popups/SimSwitchingWindow.hpp
  products/PurePhone/apps/Application.cpp
  products/PurePhone/services/appmgr/ApplicationManager.cpp
  pure_changelog.md
Labels: gui

#4165 [MOS-827] Fix looping on the SIM card selection screen
  module-apps/application-onboarding/ApplicationOnBoarding.cpp
  module-apps/apps-common/locks/handlers/SimLockSubject.cpp
  pure_changelog.md
Labels: bug
