Repository mudita/MuditaOS, pull requests merged in 2022-08, with the labels that each got.

#3999 Fix Mudita Center synchronization fail
  module-services/service-desktop/WorkerDesktop.cpp
  module-services/service-desktop/WorkerDesktop.hpp
Labels: bug

#4005 [MOS-638] Fix poor phone responsiveness
  module-services/service-eink/ServiceEink.cpp
Labels: bug

#4023 [MOS-648] Fix USB connection/disconnection detection
  module-bsp/board/linux/hal/battery_charger/BatteryCharger.cpp
  module-bsp/board/rt1051/bellpx/hal/battery_charger/BatteryCharger.cpp
  module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.cpp
  module-bsp/board/rt1051/puretx/bsp/battery_charger/battery_charger.hpp
  module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
  module-bsp/hal/include/hal/battery_charger/AbstractBatteryCharger.hpp
  module-services/service-evtmgr/battery/BatteryController.cpp
  module-services/service-evtmgr/battery/BatteryController.hpp
  pure_changelog.md
Labels: bug, desktop, hw

#4041 [MOS-74] Fix wrong tethering popup order
  module-services/service-desktop/ServiceDesktop.cpp
  pure_changelog.md
Labels: bug, desktop-service

#3970 [MOS-650] Fix spelling mistakes in README
  README.md
Labels: community

#4039 [MOS-676] Fix destroying wrong sentinels
  module-sys/SystemManager/GovernorSentinelOperations.cpp
  module-sys/SystemManager/tests/unittest_CpuSentinelsGovernor.cpp
  pure_changelog.md
Labels: bug

#4046 [MOS-74] Fix wrong tethering popup order
  module-services/service-desktop/ServiceDesktop.cpp
  module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
Labels: bug, desktop

#4045 [MOS-662][MOS-301] Fix Eink shutdown while restoring data
  module-services/service-eink/ServiceEink.cpp
  module-sys/SystemManager/SystemManagerCommon.cpp
  module-sys/SystemManager/include/SystemManager/SystemManagerCommon.hpp
  pure_changelog.md
Labels: bug, system
