Repository mudita/MuditaOS, pull requests merged in 2022-01, with the labels that each got.

#3467 [EGD-8141] Fix brownout handling while charging
  module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.cpp
  module-bsp/board/rt1051/puretx/hal/battery_charger/BatteryCharger.hpp
Labels: bug, hw, team-delta

#3486 [EGD-8156] Fix cellular on system close whitelists
  module-services/service-cellular/service-cellular/Constans.hpp
  module-sys/SystemManager/SystemManagerCommon.cpp
Labels: team-delta

#3499 [EGD-8161] Fix proper info on call with no sim
  module-apps/application-call/ApplicationCall.cpp
Labels: team-delta

#3483 [EGD-8138] Software closing procedure improved
  module-bluetooth/Bluetooth/BluetoothWorker.cpp
  module-bluetooth/Bluetooth/BluetoothWorker.hpp
  module-services/service-bluetooth/ServiceBluetooth.cpp
  module-services/service-desktop/ServiceDesktop.cpp
  module-services/service-desktop/WorkerDesktop.cpp
  module-services/service-desktop/WorkerDesktop.hpp
  module-services/service-desktop/include/service-desktop/ServiceDesktop.hpp
  module-services/service-time/ServiceTime.cpp
  module-sys/SystemManager/SystemManagerCommon.cpp
Labels: team-delta

#3501 [CP-988] Fix reporting of storage size
  products/BellHybrid/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
  products/BellHybrid/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp
  products/PurePhone/services/desktop/endpoints/deviceInfo/DeviceInfoEndpoint.cpp
  products/PurePhone/services/desktop/endpoints/include/endpoints/deviceInfo/DeviceInfoEndpoint.hpp
Labels: desktop-service, vfs

#3517 [EGD-8168] Fix Fixed lock screen in Calendar and Meditation
  module-apps/application-calendar/ApplicationCalendar.cpp
  module-apps/application-meditation/ApplicationMeditation.cpp
Labels: team-delta

#3512 [EGD-6991] Message from the operator is not fully shown
  module-cellular/at/Commands.hpp
  module-services/service-cellular/ServiceCellular.cpp
Labels: cellular

#3528 [EGD-8191] Magnetometer deinitialisation
  module-bsp/board/linux/magnetometer/magnetometer.cpp
  module-bsp/board/rt1051/bsp/magnetometer/magnetometer.cpp
  module-bsp/bsp/magnetometer/magnetometer.hpp
  products/PurePhone/services/evtmgr/WorkerEvent.cpp
Labels: hw, team-delta
