Repository mudita/MuditaOS, pull requests merged in 2024-08, with the labels that each got.

#4855 [BH-1716] Add versioning for private assets
  cmake/modules/DownloadAsset.cmake
  harmony_changelog.md
  products/BellHybrid/CMakeLists.txt
  products/BellHybrid/assets/assets_proprietary.json
Labels: enhancement

#4862 [BH-1476] Add greetings in all languages
  harmony_changelog.md
  image/system_a/data/lang/Deutsch.json
  image/system_a/data/lang/English.json
  image/system_a/data/lang/Espanol.json
  image/system_a/data/lang/Francais.json
  image/system_a/data/lang/Polski.json
Labels: feature

#4860 [BH-2054] Fix build with CONFIG_ENABLE_TEMP set to ON
  module-services/service-evtmgr/service-evtmgr/EventManagerCommon.hpp
  products/BellHybrid/apps/application-bell-main/presenters/StateController.cpp
  products/BellHybrid/apps/application-bell-settings/models/LayoutModel.cpp
  products/BellHybrid/apps/application-bell-settings/models/TemperatureUnitModel.cpp
  products/BellHybrid/apps/application-bell-settings/presenter/LayoutWindowPresenter.cpp
  products/BellHybrid/apps/common/include/common/layouts/BaseHomeScreenLayoutProvider.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassic.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithAmPm.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithBattery.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithDate.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithQuotes.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithQuotesAmPm.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutClassicWithTemp.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutNames.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutVertical.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutVerticalSimple.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutVerticalWithAmPm.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayoutVerticalWithDate.hpp
  products/BellHybrid/apps/common/include/common/layouts/HomeScreenLayouts.hpp
  products/BellHybrid/apps/common/include/common/layouts/ShortcutsLayoutProvider.hpp
  products/BellHybrid/apps/common/include/common/layouts/ShortcutsLayouts.hpp
  products/BellHybrid/apps/common/include/common/layouts/UpdateInstructionLayoutClassic.hpp
  products/BellHybrid/apps/common/include/common/layouts/UpdateInstructionLayoutProvider.hpp
  products/BellHybrid/apps/common/include/common/layouts/UpdateInstructionLayouts.hpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassic.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithAmPm.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithBattery.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithDate.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithQuotesAmPm.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutClassicWithTemp.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVertical.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVerticalSimple.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVerticalWithAmPm.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayoutVerticalWithDate.cpp
  products/BellHybrid/apps/common/src/layouts/HomeScreenLayouts.cpp
  products/BellHybrid/apps/common/src/layouts/ShortcutsLayoutClassic.cpp
  products/BellHybrid/apps/common/src/layouts/UpdateInstructionLayoutClassic.cpp
  products/BellHybrid/services/evtmgr/EventManager.cpp
Labels: bugfix

#4869 [BH-2056] Add bedside lamp settings
  harmony_changelog.md
  image/system_a/data/lang/Deutsch.json
  image/system_a/data/lang/English.json
  image/system_a/data/lang/Espanol.json
  image/system_a/data/lang/Francais.json
  image/system_a/data/lang/Polski.json
  module-services/service-db/agents/settings/Settings.cpp
  module-services/service-db/agents/settings/SystemSettings.hpp
  module-services/service-evtmgr/backlight-handler/BacklightHandlerCommon.cpp
  module-services/service-evtmgr/screen-light-control/ScreenLightControl.hpp
  products/BellHybrid/apps/application-bell-settings/ApplicationBellSettings.cpp
  products/BellHybrid/apps/application-bell-settings/CMakeLists.txt
  products/BellHybrid/apps/application-bell-settings/models/BedsideListItemProvider.cpp
  products/BellHybrid/apps/application-bell-settings/models/BedsideListItemProvider.hpp
  products/BellHybrid/apps/application-bell-settings/models/BedsideModel.cpp
  products/BellHybrid/apps/application-bell-settings/presenter/BedsidePresenter.cpp
  products/BellHybrid/apps/application-bell-settings/presenter/BedsidePresenter.hpp
  products/BellHybrid/apps/application-bell-settings/presenter/FrontlightPresenter.hpp
  products/BellHybrid/apps/application-bell-settings/windows/BellSettingsBedsideWindow.cpp
  products/BellHybrid/apps/application-bell-settings/windows/BellSettingsBedsideWindow.hpp
  products/BellHybrid/apps/application-bell-settings/windows/BellSettingsFrontlightWindow.cpp
  products/BellHybrid/apps/application-bell-settings/windows/BellSettingsFrontlightWindow.hpp
  products/BellHybrid/apps/application-bell-settings/windows/BellSettingsWindow.cpp
  products/BellHybrid/apps/common/include/common/models/BedsideModel.hpp
  products/BellHybrid/apps/common/include/common/models/FrontlightModel.hpp
  products/BellHybrid/services/db/databases/migration/settings_bell/current/90970372_Add_bedside_lamp_parameters/.meta
  products/BellHybrid/services/db/databases/migration/settings_bell/current/90970372_Add_bedside_lamp_parameters/devel.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/current/90970372_Add_bedside_lamp_parameters/down.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/current/90970372_Add_bedside_lamp_parameters/up.sql
  products/BellHybrid/services/evtmgr/backlight-handler/BacklightHandler.cpp
  products/BellHybrid/services/evtmgr/include/evtmgr/backlight-handler/BacklightHandler.hpp
Labels: feature

#4870 [BH-2061] Fix developer build
  products/PurePhone/services/desktop/endpoints/EndpointFactoryPure.cpp
Labels: bugfix, enhancement
