Repository mudita/MuditaOS, pull requests merged in 2024-09, with the labels that each got.

#4871 [BH-2062] Fix alarm volume fade in duration
  module-audio/Audio/AudioCommon.hpp
  products/BellHybrid/alarms/src/actions/PlayAudioActions.cpp
  products/BellHybrid/services/audio/VolumeFade.cpp
  products/BellHybrid/services/audio/include/audio/VolumeFade.hpp
Labels: bugfix

#4873 [BH-2065] Fix race condition between CMake targets
  CMakeLists.txt
  cmake/modules/Assets.cmake
  cmake/modules/DownloadAsset.cmake
  cmake/modules/Utils.cmake
  image/CMakeLists.txt
  module-db/tests/Helpers.cpp
  products/BellHybrid/CMakeLists.txt
  products/PurePhone/CMakeLists.txt
  test/CMakeLists.txt
Labels: bugfix

#4875 [BH-2064] Change message shown after removing alarm file
  harmony_changelog.md
  module-audio/Audio/AudioCommon.hpp
  module-audio/Audio/Operation/PlaybackOperation.cpp
  module-audio/Audio/Operation/PlaybackOperation.hpp
  products/BellHybrid/apps/application-bell-relaxation/presenter/RelaxationMainWindowPresenter.hpp
  products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.cpp
  products/BellHybrid/apps/application-bell-relaxation/windows/RelaxationMainWindow.hpp
  products/BellHybrid/apps/application-bell-settings/presenter/alarm_settings/AlarmSettingsPresenter.cpp
Labels: bugfix

#4876 [BH-2066] Enable fade effect in the relaxation app
  products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/.meta
  products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/devel.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/down.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/up.sql
Labels: feature

#4877 [BH-2067] Fix fade in for relaxation after pausing a song
  products/BellHybrid/services/audio/ServiceAudio.cpp
  products/BellHybrid/services/audio/VolumeFade.cpp
  products/BellHybrid/services/audio/include/audio/VolumeFade.hpp
Labels: bugfix

#4880 [BH-2070] Commit database migrations for 2.9.0
  products/BellHybrid/services/db/databases/databases.json
  products/BellHybrid/services/db/databases/migration/settings_bell/3/devel.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/3/down.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/3/up.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/.meta
  products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/devel.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/current/39114449_Enable_relaxation_fade_effect_by_default/up.sql
  products/BellHybrid/services/db/databases/migration/settings_bell/current/90970372_Add_bedside_lamp_parameters/.meta
  products/BellHybrid/services/db/databases/migration/settings_bell/current/90970372_Add_bedside_lamp_parameters/devel.sql
Labels: bugfix, feature

#4881 [BH-2071] Update license URL in migration tool
  tools/db_migration.py
Labels: enhancement

#4882 [BH-2067] Fix volume change during relaxation pause
  products/BellHybrid/services/audio/ServiceAudio.cpp
  products/BellHybrid/services/audio/VolumeFade.cpp
Labels: bugfix

#4883 [BH-2072] Fix power nap volume fade in duration
  module-audio/Audio/AudioCommon.hpp
  products/BellHybrid/alarms/src/actions/PlayAudioActions.cpp
  products/BellHybrid/apps/application-bell-powernap/presenter/PowerNapProgressPresenter.cpp
Labels: bugfix
